# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:\ECE 1140\ECE1140ChooChoo\Train_Model\TrainModel_UI_Iteration_1.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(710, 662)
        font = QtGui.QFont()
        font.setPointSize(8)
        MainWindow.setFont(font)
        MainWindow.setStyleSheet("")
        self.Main = QtWidgets.QWidget(MainWindow)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.Main.setFont(font)
        self.Main.setObjectName("Main")
        self.FailureBox = QtWidgets.QGroupBox(self.Main)
        self.FailureBox.setGeometry(QtCore.QRect(10, 140, 241, 251))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.FailureBox.setFont(font)
        self.FailureBox.setAutoFillBackground(True)
        self.FailureBox.setStyleSheet("")
        self.FailureBox.setFlat(False)
        self.FailureBox.setObjectName("FailureBox")
        self.FailBrake = QtWidgets.QLabel(self.FailureBox)
        self.FailBrake.setGeometry(QtCore.QRect(10, 30, 121, 63))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.FailBrake.setFont(font)
        self.FailBrake.setStyleSheet("background-color: rgb(254, 53, 53);")
        self.FailBrake.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.FailBrake.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.FailBrake.setIndent(6)
        self.FailBrake.setObjectName("FailBrake")
        self.Enabled1 = QtWidgets.QPushButton(self.FailureBox)
        self.Enabled1.setGeometry(QtCore.QRect(140, 30, 91, 31))
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.Enabled1.setFont(font)
        self.Enabled1.setStyleSheet("QPushButton {\n"
"    background: qlineargradient(spread:pad, x1:0.3, y1:0.3, x2:1, y2:1, \n"
"                                stop:0 #6eff66, stop:1 #1e7d1e); /* Light-to-dark green */\n"
"    color: black;\n"
"    font-size: 16px;\n"
"    font-weight: bold;\n"
"    border: 2px solid #1e7d1e;\n"
"    border-radius: 10px;\n"
"    padding: 6px;\n"
"    box-shadow: 5px 5px 10px rgba(0, 0, 0, 0.5); /* Raised effect */\n"
"    transition: background 0.3s ease;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background: qlineargradient(spread:pad, x1:0.3, y1:0.3, x2:1, y2:1, \n"
"                                stop:0 #00cc00, stop:1 #006600); /* Darker green when pressed */\n"
"    border: 2px solid #004d00;\n"
"    box-shadow: 2px 2px 5px rgba(0, 0, 0, 0.7); /* Shadow appears inset when pressed */\n"
"}\n"
"")
        self.Enabled1.setFlat(False)
        self.Enabled1.setObjectName("Enabled1")
        self.Disabled1 = QtWidgets.QPushButton(self.FailureBox)
        self.Disabled1.setGeometry(QtCore.QRect(140, 62, 91, 31))
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.Disabled1.setFont(font)
        self.Disabled1.setStyleSheet("QPushButton {\n"
"    background: qlineargradient(spread:pad, x1:0.3, y1:0.3, x2:1, y2:1, \n"
"                                stop:0 #ff6a6c, stop:1 #d33032); /* Light-to-dark red */\n"
"    color: black;\n"
"    font-size: 16px;\n"
"    font-weight: bold;\n"
"    border: 2px solid #d33032;\n"
"    border-radius: 10px;\n"
"    padding: 6px;\n"
"    box-shadow: 5px 5px 10px rgba(0, 0, 0, 0.5); /* Raised effect */\n"
"    transition: background 0.3s ease;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background: qlineargradient(spread:pad, x1:0.3, y1:0.3, x2:1, y2:1, \n"
"                                stop:0 #e84547, stop:1 #9c1e1f); /* Darker red when pressed */\n"
"    border: 2px solid #7a1c1d;\n"
"    box-shadow: 2px 2px 5px rgba(0, 0, 0, 0.7); /* Shadow appears inset when pressed */\n"
"}\n"
"")
        self.Disabled1.setDefault(False)
        self.Disabled1.setFlat(False)
        self.Disabled1.setObjectName("Disabled1")
        self.FailSignal = QtWidgets.QLabel(self.FailureBox)
        self.FailSignal.setGeometry(QtCore.QRect(10, 100, 121, 63))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.FailSignal.setFont(font)
        self.FailSignal.setStyleSheet("background-color: rgb(254, 53, 53);")
        self.FailSignal.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.FailSignal.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.FailSignal.setIndent(6)
        self.FailSignal.setObjectName("FailSignal")
        self.FailEngine = QtWidgets.QLabel(self.FailureBox)
        self.FailEngine.setGeometry(QtCore.QRect(10, 170, 121, 63))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.FailEngine.setFont(font)
        self.FailEngine.setStyleSheet("background-color: rgb(254, 53, 53);")
        self.FailEngine.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.FailEngine.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.FailEngine.setIndent(3)
        self.FailEngine.setObjectName("FailEngine")
        self.Enabled2 = QtWidgets.QPushButton(self.FailureBox)
        self.Enabled2.setGeometry(QtCore.QRect(140, 100, 91, 31))
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        font.setKerning(True)
        self.Enabled2.setFont(font)
        self.Enabled2.setStyleSheet("QPushButton {\n"
"    background: qlineargradient(spread:pad, x1:0.3, y1:0.3, x2:1, y2:1, \n"
"                                stop:0 #6eff66, stop:1 #1e7d1e); /* Light-to-dark green */\n"
"    color: black;\n"
"    font-size: 16px;\n"
"    font-weight: bold;\n"
"    border: 2px solid #1e7d1e;\n"
"    border-radius: 10px;\n"
"    padding: 6px;\n"
"    box-shadow: 5px 5px 10px rgba(0, 0, 0, 0.5); /* Raised effect */\n"
"    transition: background 0.3s ease;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background: qlineargradient(spread:pad, x1:0.3, y1:0.3, x2:1, y2:1, \n"
"                                stop:0 #00cc00, stop:1 #006600); /* Darker green when pressed */\n"
"    border: 2px solid #004d00;\n"
"    box-shadow: 2px 2px 5px rgba(0, 0, 0, 0.7); /* Shadow appears inset when pressed */\n"
"}\n"
"")
        self.Enabled2.setFlat(False)
        self.Enabled2.setObjectName("Enabled2")
        self.Disabled2 = QtWidgets.QPushButton(self.FailureBox)
        self.Disabled2.setGeometry(QtCore.QRect(140, 132, 91, 31))
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.Disabled2.setFont(font)
        self.Disabled2.setStyleSheet("QPushButton {\n"
"    background: qlineargradient(spread:pad, x1:0.3, y1:0.3, x2:1, y2:1, \n"
"                                stop:0 #ff6a6c, stop:1 #d33032); /* Light-to-dark red */\n"
"    color: black;\n"
"    font-size: 16px;\n"
"    font-weight: bold;\n"
"    border: 2px solid #d33032;\n"
"    border-radius: 10px;\n"
"    padding: 6px;\n"
"    box-shadow: 5px 5px 10px rgba(0, 0, 0, 0.5); /* Raised effect */\n"
"    transition: background 0.3s ease;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background: qlineargradient(spread:pad, x1:0.3, y1:0.3, x2:1, y2:1, \n"
"                                stop:0 #e84547, stop:1 #9c1e1f); /* Darker red when pressed */\n"
"    border: 2px solid #7a1c1d;\n"
"    box-shadow: 2px 2px 5px rgba(0, 0, 0, 0.7); /* Shadow appears inset when pressed */\n"
"}\n"
"")
        self.Disabled2.setDefault(False)
        self.Disabled2.setFlat(False)
        self.Disabled2.setObjectName("Disabled2")
        self.Enabled3 = QtWidgets.QPushButton(self.FailureBox)
        self.Enabled3.setGeometry(QtCore.QRect(140, 170, 91, 31))
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.Enabled3.setFont(font)
        self.Enabled3.setStyleSheet("QPushButton {\n"
"    background: qlineargradient(spread:pad, x1:0.3, y1:0.3, x2:1, y2:1, \n"
"                                stop:0 #6eff66, stop:1 #1e7d1e); /* Light-to-dark green */\n"
"    color: black;\n"
"    font-size: 16px;\n"
"    font-weight: bold;\n"
"    border: 2px solid #1e7d1e;\n"
"    border-radius: 10px;\n"
"    padding: 6px;\n"
"    box-shadow: 5px 5px 10px rgba(0, 0, 0, 0.5); /* Raised effect */\n"
"    transition: background 0.3s ease;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background: qlineargradient(spread:pad, x1:0.3, y1:0.3, x2:1, y2:1, \n"
"                                stop:0 #00cc00, stop:1 #006600); /* Darker green when pressed */\n"
"    border: 2px solid #004d00;\n"
"    box-shadow: 2px 2px 5px rgba(0, 0, 0, 0.7); /* Shadow appears inset when pressed */\n"
"}\n"
"")
        self.Enabled3.setFlat(False)
        self.Enabled3.setObjectName("Enabled3")
        self.Disabled3 = QtWidgets.QPushButton(self.FailureBox)
        self.Disabled3.setGeometry(QtCore.QRect(140, 202, 91, 31))
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.Disabled3.setFont(font)
        self.Disabled3.setStyleSheet("QPushButton {\n"
"    background: qlineargradient(spread:pad, x1:0.3, y1:0.3, x2:1, y2:1, \n"
"                                stop:0 #ff6a6c, stop:1 #d33032); /* Light-to-dark red */\n"
"    color: black;\n"
"    font-size: 16px;\n"
"    font-weight: bold;\n"
"    border: 2px solid #d33032;\n"
"    border-radius: 10px;\n"
"    padding: 6px;\n"
"    box-shadow: 5px 5px 10px rgba(0, 0, 0, 0.5); /* Raised effect */\n"
"    transition: background 0.3s ease;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background: qlineargradient(spread:pad, x1:0.3, y1:0.3, x2:1, y2:1, \n"
"                                stop:0 #e84547, stop:1 #9c1e1f); /* Darker red when pressed */\n"
"    border: 2px solid #7a1c1d;\n"
"    box-shadow: 2px 2px 5px rgba(0, 0, 0, 0.7); /* Shadow appears inset when pressed */\n"
"}\n"
"")
        self.Disabled3.setDefault(False)
        self.Disabled3.setFlat(False)
        self.Disabled3.setObjectName("Disabled3")
        self.Advertisements = QtWidgets.QLabel(self.Main)
        self.Advertisements.setGeometry(QtCore.QRect(10, 5, 685, 83))
        self.Advertisements.setMinimumSize(QtCore.QSize(0, 0))
        self.Advertisements.setAutoFillBackground(True)
        self.Advertisements.setStyleSheet("")
        self.Advertisements.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.Advertisements.setFrameShadow(QtWidgets.QFrame.Plain)
        self.Advertisements.setText("")
        self.Advertisements.setTextFormat(QtCore.Qt.AutoText)
        self.Advertisements.setScaledContents(False)
        self.Advertisements.setObjectName("Advertisements")
        self.Announcement_2 = QtWidgets.QLabel(self.Main)
        self.Announcement_2.setGeometry(QtCore.QRect(224, 90, 471, 47))
        self.Announcement_2.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.Announcement_2.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.Announcement_2.setFrameShadow(QtWidgets.QFrame.Plain)
        self.Announcement_2.setObjectName("Announcement_2")
        self.button_emergency = QtWidgets.QPushButton(self.Main)
        self.button_emergency.setGeometry(QtCore.QRect(30, 400, 206, 206))
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.button_emergency.setFont(font)
        self.button_emergency.setStyleSheet("QPushButton#button_emergency {\n"
"    background-color: red;\n"
"    color: white;\n"
"    font-size: 30px;  /* Bigger text */\n"
"    font-weight: bold;\n"
"    border: 3px solid black;\n"
"    border-radius: 100px;  /* Half of width/height for a perfect circle */\n"
"    min-width: 200px;\n"
"    min-height: 200px;\n"
"    \n"
"    /* 3D Effect using Gradient */\n"
"    background: qlineargradient(spread:pad, x1:0.3, y1:0.3, x2:1, y2:1, \n"
"                                stop:0 #ff4d4d, stop:1 #cc0000);\n"
"    \n"
"    /* Shadow effect */\n"
"    box-shadow: 5px 5px 10px rgba(0, 0, 0, 0.5);\n"
"}\n"
"\n"
"QPushButton#button_emergency:pressed {\n"
"    background-color: darkred;\n"
"    border: 3px solid #660000;\n"
"    \n"
"    /* Inset shadow to look pressed */\n"
"    background: qlineargradient(spread:pad, x1:0.3, y1:0.3, x2:1, y2:1, \n"
"                                stop:0 #cc0000, stop:1 #660000);\n"
"}\n"
"")
        self.button_emergency.setFlat(False)
        self.button_emergency.setObjectName("button_emergency")
        self.line = QtWidgets.QFrame(self.Main)
        self.line.setGeometry(QtCore.QRect(254, 150, 16, 461))
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.line_2 = QtWidgets.QFrame(self.Main)
        self.line_2.setGeometry(QtCore.QRect(498, 150, 16, 461))
        self.line_2.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.LiveTrainData = QtWidgets.QGroupBox(self.Main)
        self.LiveTrainData.setGeometry(QtCore.QRect(510, 140, 185, 391))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.LiveTrainData.setFont(font)
        self.LiveTrainData.setAutoFillBackground(True)
        self.LiveTrainData.setStyleSheet("")
        self.LiveTrainData.setFlat(False)
        self.LiveTrainData.setObjectName("LiveTrainData")
        self.gridLayoutWidget = QtWidgets.QWidget(self.LiveTrainData)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(0, 30, 183, 351))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.LiveTrainDataGrid = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.LiveTrainDataGrid.setContentsMargins(5, 0, 0, 0)
        self.LiveTrainDataGrid.setSpacing(0)
        self.LiveTrainDataGrid.setObjectName("LiveTrainDataGrid")
        self.CrewCountLabel = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.CrewCountLabel.setFont(font)
        self.CrewCountLabel.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.CrewCountLabel.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.CrewCountLabel.setObjectName("CrewCountLabel")
        self.LiveTrainDataGrid.addWidget(self.CrewCountLabel, 7, 0, 1, 1)
        self.PassengerCountLabel = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.PassengerCountLabel.setFont(font)
        self.PassengerCountLabel.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.PassengerCountLabel.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.PassengerCountLabel.setObjectName("PassengerCountLabel")
        self.LiveTrainDataGrid.addWidget(self.PassengerCountLabel, 6, 0, 1, 1)
        self.WidthLabel = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.WidthLabel.setFont(font)
        self.WidthLabel.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.WidthLabel.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.WidthLabel.setObjectName("WidthLabel")
        self.LiveTrainDataGrid.addWidget(self.WidthLabel, 4, 0, 1, 1)
        self.CommandedSpeedLabel = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.CommandedSpeedLabel.setFont(font)
        self.CommandedSpeedLabel.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.CommandedSpeedLabel.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.CommandedSpeedLabel.setObjectName("CommandedSpeedLabel")
        self.LiveTrainDataGrid.addWidget(self.CommandedSpeedLabel, 0, 0, 1, 1)
        self.SpeedLimitLabel = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.SpeedLimitLabel.setFont(font)
        self.SpeedLimitLabel.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.SpeedLimitLabel.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.SpeedLimitLabel.setObjectName("SpeedLimitLabel")
        self.LiveTrainDataGrid.addWidget(self.SpeedLimitLabel, 1, 0, 1, 1)
        self.LengthVehicleLabel = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.LengthVehicleLabel.setFont(font)
        self.LengthVehicleLabel.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.LengthVehicleLabel.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.LengthVehicleLabel.setObjectName("LengthVehicleLabel")
        self.LiveTrainDataGrid.addWidget(self.LengthVehicleLabel, 2, 0, 1, 1)
        self.MassVehicleLabel = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.MassVehicleLabel.setFont(font)
        self.MassVehicleLabel.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.MassVehicleLabel.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.MassVehicleLabel.setObjectName("MassVehicleLabel")
        self.LiveTrainDataGrid.addWidget(self.MassVehicleLabel, 5, 0, 1, 1)
        self.HeightLabel = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.HeightLabel.setFont(font)
        self.HeightLabel.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.HeightLabel.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.HeightLabel.setObjectName("HeightLabel")
        self.LiveTrainDataGrid.addWidget(self.HeightLabel, 3, 0, 1, 1)
        self.CommandedSpeedValue = QtWidgets.QLCDNumber(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.CommandedSpeedValue.setFont(font)
        self.CommandedSpeedValue.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.CommandedSpeedValue.setObjectName("CommandedSpeedValue")
        self.LiveTrainDataGrid.addWidget(self.CommandedSpeedValue, 0, 1, 1, 1)
        self.SpeedLimitValue = QtWidgets.QLCDNumber(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.SpeedLimitValue.setFont(font)
        self.SpeedLimitValue.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.SpeedLimitValue.setObjectName("SpeedLimitValue")
        self.LiveTrainDataGrid.addWidget(self.SpeedLimitValue, 1, 1, 1, 1)
        self.LengthVehicleValue = QtWidgets.QLCDNumber(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.LengthVehicleValue.setFont(font)
        self.LengthVehicleValue.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.LengthVehicleValue.setObjectName("LengthVehicleValue")
        self.LiveTrainDataGrid.addWidget(self.LengthVehicleValue, 2, 1, 1, 1)
        self.HeightValue = QtWidgets.QLCDNumber(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.HeightValue.setFont(font)
        self.HeightValue.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.HeightValue.setObjectName("HeightValue")
        self.LiveTrainDataGrid.addWidget(self.HeightValue, 3, 1, 1, 1)
        self.WidthValue = QtWidgets.QLCDNumber(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.WidthValue.setFont(font)
        self.WidthValue.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.WidthValue.setObjectName("WidthValue")
        self.LiveTrainDataGrid.addWidget(self.WidthValue, 4, 1, 1, 1)
        self.MassVehicleValue = QtWidgets.QLCDNumber(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.MassVehicleValue.setFont(font)
        self.MassVehicleValue.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.MassVehicleValue.setObjectName("MassVehicleValue")
        self.LiveTrainDataGrid.addWidget(self.MassVehicleValue, 5, 1, 1, 1)
        self.PassengerCountValue = QtWidgets.QLCDNumber(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.PassengerCountValue.setFont(font)
        self.PassengerCountValue.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.PassengerCountValue.setObjectName("PassengerCountValue")
        self.LiveTrainDataGrid.addWidget(self.PassengerCountValue, 6, 1, 1, 1)
        self.CrewCountValue = QtWidgets.QLCDNumber(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.CrewCountValue.setFont(font)
        self.CrewCountValue.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.CrewCountValue.setObjectName("CrewCountValue")
        self.LiveTrainDataGrid.addWidget(self.CrewCountValue, 7, 1, 1, 1)
        self.gridLayoutWidget_2 = QtWidgets.QWidget(self.Main)
        self.gridLayoutWidget_2.setGeometry(QtCore.QRect(270, 150, 231, 215))
        self.gridLayoutWidget_2.setObjectName("gridLayoutWidget_2")
        self.TrainControllerDetails = QtWidgets.QGridLayout(self.gridLayoutWidget_2)
        self.TrainControllerDetails.setContentsMargins(0, 0, 0, 0)
        self.TrainControllerDetails.setObjectName("TrainControllerDetails")
        self.Acceleration = QtWidgets.QLabel(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.Acceleration.setFont(font)
        self.Acceleration.setStyleSheet("background-color: rgb(168, 168, 168);")
        self.Acceleration.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.Acceleration.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.Acceleration.setObjectName("Acceleration")
        self.TrainControllerDetails.addWidget(self.Acceleration, 1, 0, 1, 1)
        self.AccValue = QtWidgets.QLCDNumber(self.gridLayoutWidget_2)
        self.AccValue.setFrameShape(QtWidgets.QFrame.Panel)
        self.AccValue.setFrameShadow(QtWidgets.QFrame.Plain)
        self.AccValue.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.AccValue.setObjectName("AccValue")
        self.TrainControllerDetails.addWidget(self.AccValue, 1, 1, 1, 1)
        self.SpeedValue = QtWidgets.QLCDNumber(self.gridLayoutWidget_2)
        self.SpeedValue.setFrameShape(QtWidgets.QFrame.Panel)
        self.SpeedValue.setFrameShadow(QtWidgets.QFrame.Plain)
        self.SpeedValue.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.SpeedValue.setObjectName("SpeedValue")
        self.TrainControllerDetails.addWidget(self.SpeedValue, 2, 1, 1, 1)
        self.Power = QtWidgets.QLabel(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.Power.setFont(font)
        self.Power.setStyleSheet("background-color: rgb(168, 168, 168);")
        self.Power.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.Power.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.Power.setIndent(6)
        self.Power.setObjectName("Power")
        self.TrainControllerDetails.addWidget(self.Power, 0, 0, 1, 1)
        self.ActualSpeed = QtWidgets.QLabel(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.ActualSpeed.setFont(font)
        self.ActualSpeed.setStyleSheet("background-color: rgb(168, 168, 168);")
        self.ActualSpeed.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.ActualSpeed.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.ActualSpeed.setObjectName("ActualSpeed")
        self.TrainControllerDetails.addWidget(self.ActualSpeed, 2, 0, 1, 1)
        self.PowerValue = QtWidgets.QLCDNumber(self.gridLayoutWidget_2)
        self.PowerValue.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.PowerValue.setFrameShape(QtWidgets.QFrame.Box)
        self.PowerValue.setFrameShadow(QtWidgets.QFrame.Plain)
        self.PowerValue.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.PowerValue.setObjectName("PowerValue")
        self.TrainControllerDetails.addWidget(self.PowerValue, 0, 1, 1, 1)
        self.CabinTemperature = QtWidgets.QGroupBox(self.Main)
        self.CabinTemperature.setGeometry(QtCore.QRect(510, 530, 181, 81))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.CabinTemperature.setFont(font)
        self.CabinTemperature.setObjectName("CabinTemperature")
        self.Temperature = QtWidgets.QLabel(self.CabinTemperature)
        self.Temperature.setGeometry(QtCore.QRect(16, 23, 151, 51))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.Temperature.setFont(font)
        self.Temperature.setStyleSheet("background-color: rgb(168, 168, 168);")
        self.Temperature.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.Temperature.setFrameShadow(QtWidgets.QFrame.Raised)
        self.Temperature.setObjectName("Temperature")
        self.line_3 = QtWidgets.QFrame(self.Main)
        self.line_3.setGeometry(QtCore.QRect(273, 365, 221, 16))
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.gridLayoutWidget_3 = QtWidgets.QWidget(self.Main)
        self.gridLayoutWidget_3.setGeometry(QtCore.QRect(270, 380, 231, 234))
        self.gridLayoutWidget_3.setObjectName("gridLayoutWidget_3")
        self.DoorsLightsBrakes = QtWidgets.QGridLayout(self.gridLayoutWidget_3)
        self.DoorsLightsBrakes.setContentsMargins(0, 0, 0, 0)
        self.DoorsLightsBrakes.setObjectName("DoorsLightsBrakes")
        self.ServiceBrakesOn = QtWidgets.QLabel(self.gridLayoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.ServiceBrakesOn.setFont(font)
        self.ServiceBrakesOn.setFrameShape(QtWidgets.QFrame.Box)
        self.ServiceBrakesOn.setObjectName("ServiceBrakesOn")
        self.DoorsLightsBrakes.addWidget(self.ServiceBrakesOn, 0, 1, 1, 1)
        self.ExteriorLightsLabel = QtWidgets.QLabel(self.gridLayoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.ExteriorLightsLabel.setFont(font)
        self.ExteriorLightsLabel.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.ExteriorLightsLabel.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.ExteriorLightsLabel.setObjectName("ExteriorLightsLabel")
        self.DoorsLightsBrakes.addWidget(self.ExteriorLightsLabel, 1, 0, 1, 1)
        self.ServiceBrakesOff = QtWidgets.QLabel(self.gridLayoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.ServiceBrakesOff.setFont(font)
        self.ServiceBrakesOff.setFrameShape(QtWidgets.QFrame.Box)
        self.ServiceBrakesOff.setObjectName("ServiceBrakesOff")
        self.DoorsLightsBrakes.addWidget(self.ServiceBrakesOff, 0, 2, 1, 1)
        self.ServiceBrakesLabel = QtWidgets.QLabel(self.gridLayoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.ServiceBrakesLabel.setFont(font)
        self.ServiceBrakesLabel.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.ServiceBrakesLabel.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.ServiceBrakesLabel.setObjectName("ServiceBrakesLabel")
        self.DoorsLightsBrakes.addWidget(self.ServiceBrakesLabel, 0, 0, 1, 1)
        self.InteriorLightsLabel = QtWidgets.QLabel(self.gridLayoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.InteriorLightsLabel.setFont(font)
        self.InteriorLightsLabel.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.InteriorLightsLabel.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.InteriorLightsLabel.setObjectName("InteriorLightsLabel")
        self.DoorsLightsBrakes.addWidget(self.InteriorLightsLabel, 2, 0, 1, 1)
        self.LeftDoorLabel = QtWidgets.QLabel(self.gridLayoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.LeftDoorLabel.setFont(font)
        self.LeftDoorLabel.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.LeftDoorLabel.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.LeftDoorLabel.setObjectName("LeftDoorLabel")
        self.DoorsLightsBrakes.addWidget(self.LeftDoorLabel, 3, 0, 1, 1)
        self.RightDoorLabel = QtWidgets.QLabel(self.gridLayoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.RightDoorLabel.setFont(font)
        self.RightDoorLabel.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.RightDoorLabel.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.RightDoorLabel.setObjectName("RightDoorLabel")
        self.DoorsLightsBrakes.addWidget(self.RightDoorLabel, 4, 0, 1, 1)
        self.ExteriorLightsOn = QtWidgets.QLabel(self.gridLayoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.ExteriorLightsOn.setFont(font)
        self.ExteriorLightsOn.setFrameShape(QtWidgets.QFrame.Box)
        self.ExteriorLightsOn.setObjectName("ExteriorLightsOn")
        self.DoorsLightsBrakes.addWidget(self.ExteriorLightsOn, 1, 1, 1, 1)
        self.ExteriorLightsOff = QtWidgets.QLabel(self.gridLayoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.ExteriorLightsOff.setFont(font)
        self.ExteriorLightsOff.setFrameShape(QtWidgets.QFrame.Box)
        self.ExteriorLightsOff.setObjectName("ExteriorLightsOff")
        self.DoorsLightsBrakes.addWidget(self.ExteriorLightsOff, 1, 2, 1, 1)
        self.InteriorLightsOn = QtWidgets.QLabel(self.gridLayoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.InteriorLightsOn.setFont(font)
        self.InteriorLightsOn.setFrameShape(QtWidgets.QFrame.Box)
        self.InteriorLightsOn.setObjectName("InteriorLightsOn")
        self.DoorsLightsBrakes.addWidget(self.InteriorLightsOn, 2, 1, 1, 1)
        self.InteriorLightsOff = QtWidgets.QLabel(self.gridLayoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.InteriorLightsOff.setFont(font)
        self.InteriorLightsOff.setFrameShape(QtWidgets.QFrame.Box)
        self.InteriorLightsOff.setObjectName("InteriorLightsOff")
        self.DoorsLightsBrakes.addWidget(self.InteriorLightsOff, 2, 2, 1, 1)
        self.LeftDoorOpen = QtWidgets.QLabel(self.gridLayoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.LeftDoorOpen.setFont(font)
        self.LeftDoorOpen.setFrameShape(QtWidgets.QFrame.Box)
        self.LeftDoorOpen.setObjectName("LeftDoorOpen")
        self.DoorsLightsBrakes.addWidget(self.LeftDoorOpen, 3, 1, 1, 1)
        self.LeftDoorClosed = QtWidgets.QLabel(self.gridLayoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.LeftDoorClosed.setFont(font)
        self.LeftDoorClosed.setFrameShape(QtWidgets.QFrame.Box)
        self.LeftDoorClosed.setObjectName("LeftDoorClosed")
        self.DoorsLightsBrakes.addWidget(self.LeftDoorClosed, 3, 2, 1, 1)
        self.RightDoorOpen = QtWidgets.QLabel(self.gridLayoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.RightDoorOpen.setFont(font)
        self.RightDoorOpen.setFrameShape(QtWidgets.QFrame.Box)
        self.RightDoorOpen.setObjectName("RightDoorOpen")
        self.DoorsLightsBrakes.addWidget(self.RightDoorOpen, 4, 1, 1, 1)
        self.RightDoorClosed = QtWidgets.QLabel(self.gridLayoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.RightDoorClosed.setFont(font)
        self.RightDoorClosed.setFrameShape(QtWidgets.QFrame.Box)
        self.RightDoorClosed.setObjectName("RightDoorClosed")
        self.DoorsLightsBrakes.addWidget(self.RightDoorClosed, 4, 2, 1, 1)
        self.Clock_12 = QtWidgets.QLCDNumber(self.Main)
        self.Clock_12.setGeometry(QtCore.QRect(563, 97, 81, 31))
        self.Clock_12.setObjectName("Clock_12")
        self.AM_PM = QtWidgets.QLabel(self.Main)
        self.AM_PM.setGeometry(QtCore.QRect(650, 97, 31, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.AM_PM.setFont(font)
        self.AM_PM.setObjectName("AM_PM")
        self.Announcement_1 = QtWidgets.QLabel(self.Main)
        self.Announcement_1.setGeometry(QtCore.QRect(10, 90, 211, 47))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.Announcement_1.setFont(font)
        self.Announcement_1.setMouseTracking(True)
        self.Announcement_1.setAutoFillBackground(True)
        self.Announcement_1.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.Announcement_1.setObjectName("Announcement_1")
        self.FailureBox.raise_()
        self.Announcement_2.raise_()
        self.button_emergency.raise_()
        self.line.raise_()
        self.line_2.raise_()
        self.LiveTrainData.raise_()
        self.gridLayoutWidget_2.raise_()
        self.CabinTemperature.raise_()
        self.line_3.raise_()
        self.gridLayoutWidget_3.raise_()
        self.Clock_12.raise_()
        self.AM_PM.raise_()
        self.Announcement_1.raise_()
        self.Advertisements.raise_()
        MainWindow.setCentralWidget(self.Main)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 710, 21))
        self.menubar.setObjectName("menubar")
        self.menuTrain_ID_1 = QtWidgets.QMenu(self.menubar)
        self.menuTrain_ID_1.setObjectName("menuTrain_ID_1")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menubar.addAction(self.menuTrain_ID_1.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.FailureBox.setTitle(_translate("MainWindow", "Failure Box"))
        self.FailBrake.setText(_translate("MainWindow", "Brake Failure"))
        self.Enabled1.setText(_translate("MainWindow", "Enabled"))
        self.Disabled1.setText(_translate("MainWindow", "Disabled"))
        self.FailSignal.setText(_translate("MainWindow", "Signal Failure"))
        self.FailEngine.setText(_translate("MainWindow", "Engine Failure"))
        self.Enabled2.setText(_translate("MainWindow", "Enabled"))
        self.Disabled2.setText(_translate("MainWindow", "Disabled"))
        self.Enabled3.setText(_translate("MainWindow", "Enabled"))
        self.Disabled3.setText(_translate("MainWindow", "Disabled"))
        self.Announcement_2.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:14pt;\">Next stop is Edgebrook</span></p></body></html>"))
        self.button_emergency.setText(_translate("MainWindow", "Emergency \n"
"Brake"))
        self.LiveTrainData.setTitle(_translate("MainWindow", "Live Train Data"))
        self.CrewCountLabel.setText(_translate("MainWindow", "Crew Count"))
        self.PassengerCountLabel.setText(_translate("MainWindow", "Passenger \n"
"Count"))
        self.WidthLabel.setText(_translate("MainWindow", "Width (ft)"))
        self.CommandedSpeedLabel.setText(_translate("MainWindow", "<html><head/><body><p>Commanded </p><p>Speed (mph)</p></body></html>"))
        self.SpeedLimitLabel.setText(_translate("MainWindow", "Speed Limit \n"
"(mph)"))
        self.LengthVehicleLabel.setText(_translate("MainWindow", "Length of \n"
"Vehicle (ft)"))
        self.MassVehicleLabel.setText(_translate("MainWindow", "Mass of Vehicle \n"
"(lbs)"))
        self.HeightLabel.setText(_translate("MainWindow", "Height (ft)"))
        self.Acceleration.setText(_translate("MainWindow", "<html><head/><body><p>Acceleration </p><p>(ft/s<span style=\" vertical-align:super;\">2</span>)</p></body></html>"))
        self.Power.setText(_translate("MainWindow", "<html><head/><body><p>Current Engine</p><p>Power (W)</p></body></html>"))
        self.ActualSpeed.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:12pt;\">Actual </span></p><p><span style=\" font-size:12pt;\">Speed (mph)</span></p></body></html>"))
        self.CabinTemperature.setTitle(_translate("MainWindow", "Cabin Temperature"))
        self.Temperature.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\">68 °F</p></body></html>"))
        self.ServiceBrakesOn.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\">ON</p></body></html>"))
        self.ExteriorLightsLabel.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\">Exterior</p><p align=\"center\">Lights</p></body></html>"))
        self.ServiceBrakesOff.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\">OFF</p></body></html>"))
        self.ServiceBrakesLabel.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\">Service</p><p align=\"center\">Brakes</p></body></html>"))
        self.InteriorLightsLabel.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\">Interior</p><p align=\"center\">Lights</p></body></html>"))
        self.LeftDoorLabel.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\">Left Door</p></body></html>"))
        self.RightDoorLabel.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\">Right Door</p></body></html>"))
        self.ExteriorLightsOn.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\">ON</p></body></html>"))
        self.ExteriorLightsOff.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\">OFF</p></body></html>"))
        self.InteriorLightsOn.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\">ON</p></body></html>"))
        self.InteriorLightsOff.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\">OFF</p></body></html>"))
        self.LeftDoorOpen.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\">OPEN</p></body></html>"))
        self.LeftDoorClosed.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\">CLOSED</p></body></html>"))
        self.RightDoorOpen.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\">OPEN</p></body></html>"))
        self.RightDoorClosed.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\">CLOSED</p></body></html>"))
        self.AM_PM.setText(_translate("MainWindow", "AM"))
        self.Announcement_1.setText(_translate("MainWindow", "ANNOUNCEMENT: "))
        self.menuTrain_ID_1.setTitle(_translate("MainWindow", "Train ID 1"))
import Advertisement_1_rc
