# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'wayside_controller.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.mode_select_combo_box = QtWidgets.QComboBox(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.mode_select_combo_box.setFont(font)
        self.mode_select_combo_box.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.mode_select_combo_box.setObjectName("mode_select_combo_box")
        self.mode_select_combo_box.addItem("")
        self.mode_select_combo_box.addItem("")
        self.gridLayout_2.addWidget(self.mode_select_combo_box, 0, 0, 1, 2)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.import_plc_button = QtWidgets.QPushButton(self.centralwidget)
        self.import_plc_button.setStyleSheet("background-color: rgb(110, 255, 102);")
        self.import_plc_button.setObjectName("import_plc_button")
        self.gridLayout.addWidget(self.import_plc_button, 2, 0, 1, 1)
        self.current_filename_label = QtWidgets.QLabel(self.centralwidget)
        self.current_filename_label.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.current_filename_label.setObjectName("current_filename_label")
        self.gridLayout.addWidget(self.current_filename_label, 0, 0, 1, 1)
        self.section_select_combo_box = QtWidgets.QComboBox(self.centralwidget)
        self.section_select_combo_box.setObjectName("section_select_combo_box")
        self.section_select_combo_box.addItem("")
        self.section_select_combo_box.addItem("")
        self.section_select_combo_box.addItem("")
        self.gridLayout.addWidget(self.section_select_combo_box, 2, 1, 1, 1)
        self.select_track_label = QtWidgets.QLabel(self.centralwidget)
        self.select_track_label.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.select_track_label.setObjectName("select_track_label")
        self.gridLayout.addWidget(self.select_track_label, 0, 1, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout, 1, 0, 1, 2)
        self.junction_table = QtWidgets.QTableWidget(self.centralwidget)
        self.junction_table.setObjectName("junction_table")
        self.junction_table.setColumnCount(3)
        self.junction_table.setRowCount(3)
        item = QtWidgets.QTableWidgetItem()
        self.junction_table.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.junction_table.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.junction_table.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.junction_table.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.junction_table.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.junction_table.setHorizontalHeaderItem(2, item)
        self.gridLayout_2.addWidget(self.junction_table, 2, 0, 1, 2)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.mode_select_combo_box.setItemText(0, _translate("MainWindow", "Automatic Mode"))
        self.mode_select_combo_box.setItemText(1, _translate("MainWindow", "Maintenance Mode"))
        self.import_plc_button.setText(_translate("MainWindow", "Import PLC File"))
        self.current_filename_label.setText(_translate("MainWindow", "Current Filename:"))
        self.section_select_combo_box.setItemText(0, _translate("MainWindow", "Section A"))
        self.section_select_combo_box.setItemText(1, _translate("MainWindow", "Section B"))
        self.section_select_combo_box.setItemText(2, _translate("MainWindow", "Section C"))
        self.select_track_label.setText(_translate("MainWindow", "Select Track Section"))
        item = self.junction_table.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "1"))
        item = self.junction_table.verticalHeaderItem(1)
        item.setText(_translate("MainWindow", "2"))
        item = self.junction_table.verticalHeaderItem(2)
        item.setText(_translate("MainWindow", "3"))
        item = self.junction_table.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Junctions"))
        item = self.junction_table.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Light Signals"))
        item = self.junction_table.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Switch Signals"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
